name: logbook_app_084
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  
  # Library Driver MongoDB Atlas [cite: 213, 214]
  mongo_dart: ^0.10.8
  
  # Library untuk membaca file .env agar kredensial aman [cite: 215, 216]
  flutter_dotenv: ^6.0.0
  
  # Library untuk format tanggal dan waktu pada LogHelper [cite: 233, 234]
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0
  flutter_markdown: ^0.7.7+1
  camera: ^0.12.0+1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.6.0
  image_gallery_saver_plus: ^4.0.1
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Pendaftaran aset agar file .env bisa dibaca oleh aplikasi [cite: 224, 225]
  assets:
    - assets/images/
    - .env