name: logbook_app_084
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  
  # Library Driver MongoDB Atlas [cite: 213, 214]
  mongo_dart: ^0.10.8
  
  # Library untuk membaca file .env agar kredensial aman [cite: 215, 216]
  flutter_dotenv: ^6.0.0
  
  # Library untuk format tanggal dan waktu pada LogHelper [cite: 233, 234]
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Pendaftaran aset agar file .env bisa dibaca oleh aplikasi [cite: 224, 225]
  assets:
    - assets/images/
    - .env